# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.7'

services:

  webapp:
    image: webapp
    container_name: webapp
    build:
      dockerfile: ./webapp/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ConnectionStrings:MySqlConnection=server=friendsdb;database=friendsdb;uid=root;password=root;
    depends_on: 
      - friendsdb
    networks:
      - otus-network


  data_generator:
    image: data_generator
    container_name: data_generator
    build:
      dockerfile: ./data_generator/Dockerfile    
    environment:
      - ConnectionStrings:MySqlConnection=server=friendsdb;database=friendsdb;uid=root;password=root;
      - NumberOfProfilesToGenerate=1000000
      - WaitDatabaseReadyInSeconds=30
    depends_on: 
      - friendsdb
    networks:
      - otus-network

  friendsdb:
    image: friendsdb
    container_name: friendsdb
    build:
      dockerfile: ./friendsdb/Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=friendsdb
    volumes:  
      - friendsdb_volume:/var/lib/mysql/:delegated
    networks:
      - otus-network

volumes:
 friendsdb_volume:
 
networks:
  otus-network:
